name: Bump version and make new release
on:
  workflow_dispatch:
    inputs:
      new_version:
        type: choice
        description: New version
        required: true
        default: 'minor'
        options:
          - major
          - minor

permissions:
  contents: write
  pull-requests: write

jobs:
  version_bump:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}
    steps:
      # Checkout repository and install Python
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Update every instance of version variable
      - name: Update version number from input
        id: bump_version
        run: |
          python .github/workflows/scripts/bump_version.py
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ env.PYTHONPATH }}
          NEW_VERSION: ${{ github.event.inputs.new_version }}

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push commit
        id: commit-and-push
        run: |
          git add 'Nanolight (Lazer Edition)/skin.ini'
          git add 'Nanolight (Lazer Edition)/skininfo.json'
          git commit -S -m 'Version bump to ${{ steps.bump_version.outputs.new_version }}'
          git push
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  make_release:
    needs:
      - version_bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.version_bump.outputs.commit_hash }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Make .osk
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Nanolight (Lazer Edition).osk'
          exclusions: '/*.ai'
          directory: 'Nanolight (Lazer Edition)'

      - name: Get new release version
        id: version_to_release
        run: |
          python .github/workflows/scripts/bump_version.py
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ env.PYTHONPATH }}
          JUST_RETURN_VERSION: '1'
      - name: Make Release Draft
        uses: softprops/action-gh-release@v1
        with:
          files: "Nanolight (Lazer Edition)/Nanolight (Lazer Edition).osk"
          draft: true
          tag_name: 'nanolight-${{ steps.version_to_release.outputs.version }}'
          name: 'Nanolight ${{ steps.version_to_release.outputs.version }}'
          token: ${{ secrets.PERSONAL_TOKEN }}