name: Make new release
on:
  workflow_run:
    workflows: [Bump skin version]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  make_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'nanolight'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Make .osk
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Nanolight (Lazer Edition).osk'
          exclusions: '/*.ai'
          directory: 'Nanolight (Lazer Edition)'

      - name: Get new release version
        id: version_to_release
        run: |
          python .github/workflows/scripts/bump_version.py
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ env.PYTHONPATH }}
          JUST_RETURN_VERSION: '1'
      - name: Make Release Draft
        uses: softprops/action-gh-release@v1
        with:
          files: "Nanolight (Lazer Edition)/Nanolight (Lazer Edition).osk"
          draft: true
          tag_name: 'nanolight-${{ steps.version_to_release.outputs.version }}'
          name: 'Nanolight ${{ steps.version_to_release.outputs.version }}'
          token: ${{ secrets.PERSONAL_TOKEN }}
          target_commitish: 'nanolight'